@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDMzMDUzMzB9.vx3KxOvErI2kzKMGPK4lLH7BA5anOflw8vROXU3z6pg

@domain = http://localhost:3000

###All Products
GET {{ domain }}/products

###Show Product
GET {{ domain }}/products/5

###Products with name
GET {{ domain }}/products?search=dagger

###Discounted Products
GET {{ domain }}/products?discount=true

###Show Product
GET {{ domain }}/products/8
Authorization: Bearer {{ jwt }}

###Create Product
POST {{ domain }}/products/
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Pineapple",
  "price": 2,
  "description": "A crunchy and refreshing fruit.",
  "image_url": "https://png.pngtree.com/png-vector/20200525/ourlarge/pngtree-cute-apple-cartoon-vector-png-image_2212396.jpg",
  "supplier": "Amazon",
  "inventory": 50
  
}

###Update Product
PATCH {{ domain }}/products/16
Authorization: Bearer {{ jwt }}
Content-Type: application/json

{
  "name": "Gorilla"
}

###Destroy Product
DELETE {{ domain }}/products/15
Authorization: Bearer {{ jwt }}

###Show Supplier
GET {{ domain }}/suppliers/1

###Create Supplier
POST {{ domain }}/suppliers/
Content-Type: application/json

{
  "name": "Home Depot",
  "email": "homedepot@gmail.com",
  "phone_number": "999-9999"
  
}

###Update Supplier
PATCH {{ domain }}/suppliers/3
Content-Type: application/json

{
  "email": "homedepot@yahoo.com"
}

###Destroy Supplier
DELETE {{ domain }}/suppliers/3

### Users create (signup)
POST {{ domain }}/users
Content-Type: application/json

{
  "name": "Brian",
  "email": "brian@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST {{ domain }}/sessions
Content-Type: application/json

{
  "email": "brian@gmail.com",
  "password": "password"
}

###Orders all
GET {{ domain }}/orders
Authorization: Bearer {{ jwt }}

###Orders Show
GET {{ domain }}/orders/2
Authorization: Bearer {{ jwt }}

### Orders create
POST {{ domain }}/orders
Content-Type: application/json
Authorization: Bearer {{ jwt }}

{
  "product_id": 9,
  "quantity": 10
}

