###All Products
GET http://localhost:3000/products/

###Show Product
GET http://localhost:3000/products/16

###Create Product
POST http://localhost:3000/products/
Content-Type: application/json

{
  "name": "Socks",
  "price": 6,
  "description": "A soft cotton piece of clothing wore on feet.",
  "image_url": "https://pixy.org/src/51/514603.png",
  "inventory": 22
  
}

###Update Product
PATCH http://localhost:3000/products/16
Content-Type: application/json

{
  "name": "pillow"
}

###Destroy Product
DELETE http://localhost:3000/products/4