###All Products
GET http://localhost:3000/products

###Show Product
GET http://localhost:3000/products/5

###Products with name
GET http://localhost:3000/products?search=dagger

###Discounted Products
GET http://localhost:3000/products?discount=true

###Show Product
GET http://localhost:3000/products/8

###Create Product
POST http://localhost:3000/products/
Content-Type: application/json

{
  "name": "Socks",
  "price": 6,
  "description": "A soft cotton piece of clothing wore on feet.",
  "image_url": "https://pixy.org/src/51/514603.png",
  "inventory": 22
  
}

###Update Product
PATCH http://localhost:3000/products/16
Content-Type: application/json

{
  "name": "pillow"
}

###Destroy Product
DELETE http://localhost:3000/products/4

###Show Supplier
GET http://localhost:3000/suppliers/1

###Create Supplier
POST http://localhost:3000/suppliers/
Content-Type: application/json

{
  "name": "Home Depot",
  "email": "homedepot@gmail.com",
  "phone_number": "999-9999"
  
}

###Update Supplier
PATCH http://localhost:3000/suppliers/3
Content-Type: application/json

{
  "email": "homedepot@yahoo.com"
}

###Destroy Supplier
DELETE http://localhost:3000/suppliers/3